# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Start
        run: echo CI started!

      # Runs a set of commands using the runners shell
      - name: Setup Python
        uses: actions/setup-python@v1
        with: 
          python-version: 3.8.6

      # Runs a set of commands using the runners shell
      - name: Upgrade pip
        run: |
          pip install --upgrade pip
          
      # Runs a set of commands using the runners shell
      - name: Test environment
        run: |
          make test_environment
          
      # Runs a set of commands using the runners shell
      - name: Install dependencies
        run: |
          make requirements

      # Runs a set of commands using the runners shell
      - name: Lint
        continue-on-error: true
        run: |
          make lint

      # Runs a set of commands using the runners shell
      - name: Black
        continue-on-error: true
        run: |
          make black

      # Runs a set of commands using the runners shell
      - name: Sphinx docs
        continue-on-error: true
        run: |
          make sphinx
      
      # Archive docs
      - name: Archive docs
        uses: actions/upload-artifact@v2
        with:
          name: docs
          path: |
            docs/_build/html

      # Runs a set of commands using the runners shell
      - name: Make features from data
        run: |
          make features
      
      # Archive processed data
      - name: Archive processed data
        uses: actions/upload-artifact@v2
        with:
          name: data-features
          path: |
            data/processed/dataset.csv

      # Runs a set of commands using the runners shell
      - name: Search for hyperparameters
        continue-on-error: true
        run: |
          make hypersearch

      # Runs a set of commands using the runners shell
      - name: Train a model
        run: |
          make train

      # Runs a set of commands using the runners shell
      - name: Validate the model
        continue-on-error: true
        run: |
          make validate

      # Runs a set of commands using the runners shell
      - name: Test serving the model
        continue-on-error: true
        run: |
          make serve && make test-serve
      
      # Archive model training and hyperparameters search
      - name: Archive model training and hyperparameters search
        continue-on-error: true
        uses: actions/upload-artifact@v2
        with:
          name: model
          path: |
            models
            !models/deployment.json

      # Login to docker
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      
      # Build and push docker image
      - name: Build and push
        continue-on-error: true
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./Dockerfile
          builder: ${{ steps.buildx.outputs.name }}
          push: true
          tags: aliyad/cars-price:latest
      
      - name: Image digest
        continue-on-error: true
        run: echo ${{ steps.docker_build.outputs.digest }}
        
  dockerize:
    runs-on: ubuntu-latest
    needs: ci

    steps:
      - uses: actions/checkout@v1
      - name: Docker login
        run: docker login -u ${{ secrets.DOCKER_HUB_USERNAME }} -p ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: Build
        run: docker build -t cars-price .
      - name: Tags
        run: |
          docker tag cars-price ${{ secrets.DOCKER_HUB_USERNAME }}/cars-price:${{ github.sha }}
          docker tag cars-price ${{ secrets.DOCKER_HUB_USERNAME }}/cars-price:latest
      - name: Push
        run: |
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/cars-price:${{ github.sha }}
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/cars-price:latest